#!/bin/sh
#
# Usage:
# 1: `cp -r /etc/sv/runit-usr /etc/sv/usr/[someuser]`
# 2: `ln -s /etc/sv/usr/[someuser] /var/service/[someuser]`
# 3: You are done. Relax.
#

UID=`pwd -P`
UID=${UID##*/}

if [ -d "/home/$UID/service" ]; then
	chpst -u$UID runsvdir /home/$UID/service
fi
